version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9989:9989
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: vit
      POSTGRES_PASSWORD: p!ssword2717
      POSTGRES_DB: tasker
      TZ: GMT-3
      PGTZ: GMT-3
    ports:
      - 5432:5432
